meta_product_name: "Plantscape"
meta_title: "Plantscape - We take your plants on vacation, while you are."
meta_description: "Plantscape - We take your plants on vacation, while you are. Book a plantsitter now and let us take care of your urban jungle!
meta_image: "plantscape.png" # should exist in `app/assets/images/`
twitter_account: "@plantscape"   # required for Twitter Cards
